"""initial_schema

Revision ID: 358d9a4f78d5
Revises:
Create Date: 2026-09-26 12:03:03.983568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358d9a4f78d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_categories_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('INVENTORY_MANAGER', 'WAREHOUSE_STAFF')", name='check_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('warehouses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_code'), ['code'], unique=True)

    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.CheckConstraint("type IN ('INTERNAL', 'VENDOR_VIRTUAL', 'CUSTOMER_VIRTUAL', 'LOSS_VIRTUAL')", name='check_location_type'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_resets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('otp_code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('min_stock_level', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_stock_level', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_products_sku', ['sku'], unique=False)

    op.create_table('stock_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('source_location_id', sa.Uuid(), nullable=True),
    sa.Column('destination_location_id', sa.Uuid(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("operation_type IN ('RECEIPT', 'DELIVERY', 'INTERNAL', 'ADJUSTMENT')", name='check_operation_type'),
    sa.CheckConstraint("status IN ('DRAFT', 'WAITING', 'READY', 'DONE', 'CANCELED')", name='check_operation_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_operations', schema=None) as batch_op:
        batch_op.create_index('idx_operations_ref_status', ['reference', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_operations_reference'), ['reference'], unique=True)

    op.create_table('stock_quant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('on_hand', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', name='uq_stock_quant_product_location')
    )
    with op.batch_alter_table('stock_quant', schema=None) as batch_op:
        batch_op.create_index('idx_stock_quant_lookup', ['product_id', 'location_id'], unique=False)

    op.create_table('stock_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('from_location_id', sa.Uuid(), nullable=True),
    sa.Column('to_location_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operation_id'], ['stock_operations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_ledger', schema=None) as batch_op:
        batch_op.create_index('idx_ledger_product_time', ['product_id', 'timestamp'], unique=False)

    op.create_table('stock_operation_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_demanded', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_done', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['stock_operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_operation_lines')
    with op.batch_alter_table('stock_ledger', schema=None) as batch_op:
        batch_op.drop_index('idx_ledger_product_time')

    op.drop_table('stock_ledger')
    with op.batch_alter_table('stock_quant', schema=None) as batch_op:
        batch_op.drop_index('idx_stock_quant_lookup')

    op.drop_table('stock_quant')
    with op.batch_alter_table('stock_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_operations_reference'))
        batch_op.drop_index('idx_operations_ref_status')

    op.drop_table('stock_operations')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('idx_products_sku')

    op.drop_table('products')
    op.drop_table('otp_resets')
    op.drop_table('locations')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_code'))

    op.drop_table('warehouses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_categories_name'))

    op.drop_table('product_categories')
    # ### end Alembic commands ###
